<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');

use Magento\Framework\View\Helper\SecureHtmlRenderer;
/** @var SecureHtmlRenderer $secureRenderer */

?>
<?php if ($viewModel->isExtendEnabled()): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig(); ?>
    <?php if ($jsonConfig): ?>
        <?php $libUrl = str_replace('.js', '', $viewModel->getJsMode()); ?>
        <!-- hash_002 -->
        <?php
        $scriptString = <<<EOT
            require.config({
                paths: {
                    'extendSdk': '{$block->escapeJs($libUrl)}'
                },
                config: {
                    mixins: {
                        'Magento_Checkout/js/view/minicart': {
                            'Extend_Warranty/js/view/minicart-mixin': true
                        },
                        'Magento_Checkout/js/sidebar': {
                            'Extend_Warranty/js/sidebar-mixin': true
                        }
                    }
                }
            });

            require(['extendSdk'], function(Extend) {
                Extend.config({$jsonConfig});
                window.Extend = Extend;
        EOT;
        $integrationConfig = $viewModel->getIntegrationJsonConfig();
        if ($integrationConfig && !empty($integrationConfig)):
            $scriptString .= <<<EOT
                window.Extend.integration = {$integrationConfig};
            EOT;
        endif;
        $scriptString .= <<<EOT
            });
        EOT;

        echo $secureRenderer->renderTag('script', [], $scriptString, false);
        ?>
        <?php if ($block->getTrackingEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Extend_Warranty/js/tracking-service": {}
            }
        }
        </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
