<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isExtendEnabled()) : ?>
    <script src="<?= $viewModel->getJsMode() ?>"></script>
    <script>
        Extend.config(<?= $viewModel->getJsonConfig() ?>);
    </script>
<?php endif; ?>

<script>
    var BASE_URL = '<?= $escaper->escapeUrl($block->getBaseUrl()) ?>';
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
