<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Extend\Warranty\Block\Tracking $block
 */
?>
<script type="text/x-magento-init">
    {
      "*": {
        "Extend_Warranty/js/success": {
            "cartTotal": <?= /* @noEscape */ $block->getCartTotal(); ?>
        }
      }
    }
</script>
