<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

/** @var Magento\Sales\Block\Adminhtml\Order\View $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getViewModel();
$parentBlock = $block->getParentBlock();
$item = $parentBlock->getItem();
$leadToken = $viewModel->unserialize($item->getLeadToken()) ?? [];
?>

<?php if ($viewModel->isExtendEnabled()
    && $viewModel->isLeadEnabled()
    && !empty($leadToken)
    && !$viewModel->isWarrantyInLaterOrders($item)): ?>
    <td>
        <div id="extend-offer-<?= /* @noEscape */ str_replace([' ','"'], '', $item->getSku()); ?>"></div>
    </td>
    <script>
        require(['jquery','mage/url'], function($, urlBuilder){
            Extend.buttons.renderSimpleOffer(
                '#extend-offer-<?= /* @noEscape */ str_replace([' ','"'], '', $item->getSku()) ?>', {
                referenceId: '<?= /* @noEscape */ $item->getSku() ?>',
                onAddToCart: function (opts) {

                    const plan = opts.plan;
                    if (plan) {
                        let url      = "<?= /* @noEscape */ $block->getUrl('extend/warranty/leads') ?>";
                        let leadToken = "<?= /* @noEscape */ implode(", ", $leadToken); ?>";
                        let order = "<?= /* @noEscape */ $block->getOrder()->getId();?>";
                        let qty = "<?= /* @noEscape */ $item->getQtyOrdered(); ?>";
                        plan.product = '<?= /* @noEscape */ $item->getSku() ?>';
                        plan.qty = '<?= /* @noEscape */ $item->getQtyOrdered(); ?>';

                        $.post(url, {
                            order: order,
                            warranty: plan,
                            qty: qty,
                            leadToken : leadToken
                        }).done(function (data) {
                            if (data.status == "success") {

                                var url = data.redirect;
                                console.log(url);
                                window.location.href = url;
                            } else {
                                console.log("Oops! There was an error adding the protection plan.");
                            }
                        });
                    }
                }
            });
        });
    </script>
<?php endif; ?>
