<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

/**
 * @var \Extend\Warranty\Block\System\Config\HistoricalOrders\Button $block
 */

$scopeData = $block->getScopeData();
?>
<div class="extend-sync-button-container">
    <button id="syncBtn" data-mage-init='{"historicalOrdersSync": {
            "url": "<?= $block->escapeJs($block->getUrl('extend/orders/historicalOrders', [$scopeData['scopeType'] => $scopeData['scopeId']])) ?>",
            "resetFlagUrl": "<?= $block->escapeJs($block->getUrl('extend/products_sync/resetFlag')) ?>"
        }}' <?php if (!$block->isButtonEnabled()): ?>class="disabled"<?php endif; ?>>
        <span><?= __('Send historical Orders') ?></span>
    </button>
    <div class="sync-info">
        <p id="sync-msg">
            <label for="sync-time"><?= __('Sync: ') ?></label>
            <span id="sync-time"><?= !empty($block->getSyncPeriod()) ? $block->getSyncPeriod() : __('Never') ?></span>
        </p>
        <a id="cancel_sync">
            <span><?= __('Cancel Sync') ?></span>
        </a>
    </div>
</div>
