<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

/**
 * @var \Extend\Warranty\Block\System\Config\Products\Button $block
 */

$scopeData = $block->getScopeData();
?>
<div class="extend-sync-button-container">
    <button id="syncBtn" data-mage-init='{"productSync": {
            "url": "<?= $block->escapeJs($block->getUrl('extend/products/sync')) ?>",
            "scope": "<?= $block->escapeJs($scopeData['scope']) ?>",
            "scopeId": "<?= $block->escapeJs($scopeData['scopeId']) ?>"
        }}'>
        <span>Sync Products</span>
    </button>
    <div class="sync-info">
        <p id="sync-msg"><strong><?=__('Last Sync:').' '?></strong><span id="sync-time"><?= !empty($block->getLastSync()) ? $block->getLastSync() : 'Never'?></span></p>
        <a id="cancel_sync">Cancel Sync</a>
    </div>
</div>
