<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2023 Extend Inc. (https://www.extend.com/)
 */


namespace Extend\Warranty\Model\Api\Request\LineItem;

use Extend\Warranty\Model\Api\Request\LineItemBuilder;

class ShippingProtectionContractLineItemBuilder extends LineItemBuilder
{

    public function preparePayload()
    {
        return parent::preparePayload(); // TODO: Change the autogenerated stub
    }
}