<?php
/**
 * Extend Warranty - PDP warranty offers block
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Magento\Catalog\Block\Product\View $block
 */

/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getData('viewModel');
/** @var string $offerTypeArea */
$offerTypeArea = $block->getData('offerTypeArea');
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();
$isConfigurable = $product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE;
?>
<?php if ($viewModel->isExtendEnabled() && $product->isSaleable()): ?>
    <div class="pdp-warranty-offers" id="warranty-offers-<?= $block->escapeHtmlAttr($product->getId()) ?>"></div>

    <script type="text/x-magento-init">
    {
        "#warranty-offers-<?= $block->escapeHtmlAttr($product->getId()) ?>": {
            "productWarrantyOffers":{
                "isInProductView": true,
                "productSku": "<?= $isConfigurable ? '' : $block->escapeJs($product->getSku()) ?>",
                "buttonEnabled": <?= $block->escapeJs($viewModel->isProductDetailPageOffersEnabled() ? 1 : 0) ?>,
                "modalEnabled": <?= $block->escapeJs($viewModel->isInterstitialCartOffersEnabled() ? 1 : 0) ?>
            }
        }
    }
    </script>
<?php endif; ?>
