<?php
/**
 * Extend Warranty - Checkout Success page tracking
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Extend\Warranty\Block\Tracking $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php if ($block->getTrackingEnabled()): ?>
    <?php
    $cartTotal = $block->getCartTotal();
    $scriptString = <<<script
        require(['Extend_Warranty/js/tracking/actions', 'extendSdk'], function(actions) {
        //<![CDATA[
            actions.trackCheckoutSuccess({
                cartTotal: {$cartTotal}
            });
        //]]>
        });
script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
