<?php
/**
 * Extend Warranty - Checkout Success page tracking
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Extend\Warranty\Block\Tracking $block
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
/** @var SecureHtmlRenderer $secureRenderer */

?>

<?php if ($block->getTrackingEnabled()): ?>
    <?php $cartTotal = $block->getCartTotal(); ?>
    <?php
    $scriptString = <<<EOT
    require(['Extend_Warranty/js/extendtrk/actions', 'extendSdk'], function(actions) {
        actions.trackCheckoutSuccess({
            cartTotal: {$block->escapeJs($cartTotal)}
            });
        });

    EOT;
    echo $secureRenderer->renderTag('script', [], $scriptString, false);
    ?>
<?php endif; ?>
