<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
/** @var SecureHtmlRenderer $secureRenderer */

if ($_item = $block->getItem()):
    $_product = $_item->getProduct();

    $quote = $_item->getQuote();


    /** @var Extend\Warranty\ViewModel\Warranty $inCartViewModel */
    $inCartViewModel = $block->getData('viewModel');
    $productType = $_product->getTypeId();

    ?>

    <?php if ($_product->getTypeId() !== 'warranty'): ?>
    <?php if ($inCartViewModel->isExtendEnabled((int)$quote->getStoreId()) && $inCartViewModel->isShoppingCartOffersEnabled()): ?>
        <?php if (!$inCartViewModel->hasWarranty($quote, (int)$_item->getId())): ?>
            <tbody id="warranty-<?= /* @noEscape */
            $_item->getId() ?>">
            <tr>
                <td>
                    <div id="extend-offer-<?= /* @noEscape */
                    $_item->getId() ?>"></div>
                </td>
            </tr>

            <?php
            $scriptString = <<<EOT
                require(['jquery', 'Magento_Ui/js/modal/alert'], function ($, alert) {
                    Extend.buttons.renderSimpleOffer('#extend-offer-{$_item->getId()}', {
                        referenceId: '{$inCartViewModel->getProductSkuByQuoteItem($_item)}',
                        onAddToCart: function (opts) {

                            const plan = opts.plan;
                            if (plan) {
                EOT;
            $parentId = $_item->getOptionByCode('simple_product') ? $_item->getProductId() : '';
            $scriptString .= <<<EOT
                                let parentId = "{$parentId}";
                                let url = "{$block->getUrl('extend/warranty/add')}";
                                plan.product = '{$inCartViewModel->getProductSkuByQuoteItem($_item)}';
                                plan.secondary_sku = '{$inCartViewModel->getRelationSkuByQuoteItem($_item)}';

                                $.post(url, {
                                    warranty: plan,
                                    option: parentId
                                }).done(function (data) {
                                    if (data.status == "success") {
                                        order.itemsUpdate();
                                    } else {
                                        alert({
                                            content: data.error
                                        });
                                    }
                                });
                           } //if plan
                        }
                    });
                });
            EOT;
            echo $secureRenderer->renderTag('script', [], $scriptString, false);
            ?>
            </tbody>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
<?php endif; ?>
