<?php
if ($_item = $block->getItem()):
    $_product = $_item->getProduct();

    $quote = $_item->getQuote();

    /** @var Extend\Warranty\ViewModel\Warranty $inCartViewModel */
    $inCartViewModel = $block->getData('viewModel');
    $productType = $_product->getTypeId();

    ?>

    <?php if ($_product->getTypeId() !== 'warranty'): ?>
    <?php if ($inCartViewModel->isExtendEnabled((int)$quote->getStoreId()) && $inCartViewModel->isShoppingCartOffersEnabled()): ?>
        <?php if (!$inCartViewModel->hasWarranty($quote, (int)$_item->getId())): ?>
            <tbody id="warranty-<?= /* @noEscape */
            $_item->getId() ?>">
            <tr>
                <td>
                    <div id="extend-offer-<?= /* @noEscape */
                    $_item->getId() ?>"></div>
                </td>
            </tr>
            <script>
                require(['jquery'], function ($) {
                    Extend.buttons.renderSimpleOffer('#extend-offer-<?= /* @noEscape */ $_item->getId() ?>', {
                        referenceId: '<?= /* @noEscape */ $inCartViewModel->getProductSkuByQuoteItem($_item) ?>',
                        onAddToCart: function (opts) {

                            const plan = opts.plan;
                            if (plan) {
                                let parentId = "<?= /* @noEscape */ $_item->getOptionByCode('simple_product') ?
                                    $_item->getProductId() : '' ?>";
                                let url = "<?= /* @noEscape */ $block->getUrl('extend/warranty/add') ?>";
                                plan.product = '<?= /* @noEscape */ $inCartViewModel->getProductSkuByQuoteItem($_item) ?>';

                                $.post(url, {
                                    warranty: plan,
                                    option: parentId
                                }).done(function (data) {
                                    if (data.status == "success") {
                                        order.itemsUpdate();
                                    } else {
                                        console.log("Oops! There was an error adding the protection plan.");
                                    }
                                });
                            }
                        }
                    });
                });
            </script>
            </tbody>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
<?php endif; ?>
