<?php
/**
 * Extend Warranty - "Add Warranty" button for Lead Order
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer $block
 */

/** @var \Magento\Quote\Model\Quote\Item\AbstractItem $_item */
$_item = $block->getItem();
/** @var \Magento\Catalog\Model\Product $product */
$product = $_item->getProduct();
/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getData('viewModel');

$productType = $product->getTypeId();
$isBundle = $productType === \Magento\Bundle\Model\Product\Type::TYPE_CODE;
$bundleCheck = $isBundle && !$viewModel->isIndividualBundleItemOffersEnabled() || !$isBundle;
$isWarrantyItem = $productType === \Extend\Warranty\Model\Product\Type::TYPE_CODE;

$leadToken = $viewModel->unserialize($_item->getLeadToken()) ?? [];
$isExpired = $viewModel->isExpired((string)reset($leadToken));
?>

<?php if (!$isWarrantyItem
    && $viewModel->isOrderOffersEnabled()
    && $viewModel->isLeadEnabled()
    && isset($leadToken)
    && $bundleCheck
    && !$isExpired): ?>
    <?php $isWarrantyInLaterOrders = $viewModel->isWarrantyInLaterOrders($_item)?>
    <?php if (!$isWarrantyInLaterOrders): ?>
        <?php $isWarrantyInQuote = (int)$viewModel->isWarrantyInQuote((int)$_item->getId()) ?>
    <?php endif; ?>
    <div class="order-warranty-offers" id="warranty-offers-<?= $block->escapeHtmlAttr($_item->getId()) ?>"></div>
    <script type="text/x-magento-init">
        {
            "#warranty-offers-<?= $block->escapeHtmlAttr($_item->getId()) ?>": {
                "leadOrderWarranty":{
                    "itemId": "<?= $block->escapeJs($_item->getId()) ?>",
                    "productSku": "<?= $block->escapeJs($product->getData('sku')) ?>",
                    "qty": "<?= $block->escapeJs($_item->getQtyOrdered()) ?>",
                    "leadToken": "<?= $block->escapeJs(implode(", ", $leadToken)) ?>",
                    "addLeadUrl" : "<?= $block->escapeUrl($block->getUrl('warranty/cart/addlead')) ?>",
                    "buttonEnabled": true,
                    "trackingEnabled": <?= $block->escapeJs($viewModel->isTrackingEnabled() ? 1 : 0) ?>,
                    "isWarrantyInLaterOrders": <?= (int)$isWarrantyInLaterOrders ?>,
                    "isWarrantyInQuote": <?= $isWarrantyInQuote ?? 0 ?>
                }
            }
        }
    </script>
<?php endif; ?>
