<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

/** @var \Extend\Warranty\Block\Adminhtml\Order\Create\Installation $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');

use Magento\Framework\View\Helper\SecureHtmlRenderer;
/** @var SecureHtmlRenderer $secureRenderer */

?>

<script src="<?= /* @noEscape */ $viewModel->getJsMode() ?>"></script>

<?php
    $scriptString = <<<EOT
    var BASE_URL = '{$block->getUrl('*')}';
    var FORM_KEY = '{$block->getFormKey()}';
    var require = {
        "baseUrl": "{$block->getViewFileUrl('/')}"
    };
    EOT;

    echo $secureRenderer->renderTag('script', [], $scriptString, false);
?>

