<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
?>

<?php if ($viewModel->isExtendEnabled()): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig(); ?>
    <?php if ($jsonConfig): ?>
        <script src="<?= /* @noEscape */ $viewModel->getJsMode() ?>"></script>
        <script>
            Extend.config(<?=/* @noEscape */ $jsonConfig ?>);
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    var BASE_URL = '<?= /* @noEscape */ $block->getUrl('*') ?>';
    var FORM_KEY = '<?= /* @noEscape */ $block->getFormKey() ?>';
    var require = {
        "baseUrl": "<?= /* @noEscape */ $block->getViewFileUrl('/') ?>"
    };
</script>
