<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
/** @var SecureHtmlRenderer $secureRenderer */

/** @var \Extend\Warranty\Block\Adminhtml\Order\Create\Installation $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
$currentStoreId = $block->getCurrentStore();
?>

<?php if ($viewModel->isExtendEnabled($currentStoreId)): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig($currentStoreId); ?>
    <?php if ($jsonConfig): ?>
        <?php
        $scriptString = <<<EOT
        Extend.config({$viewModel->getJsonConfig($currentStoreId)});
        EOT;
        echo $secureRenderer->renderTag('script', [], $scriptString, false);
        ?>
    <?php endif; ?>
<?php endif; ?>