<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */
/** @var \Extend\Warranty\ViewModel\Adminhtml\Installation $viewModel */
$viewModel = $block->getData('viewModel');
$storeId = $viewModel->getCurrentStoreId();
?>
<?php if ($viewModel->isExtendEnabled($storeId)) : ?>
    <?php $jsonConfig = $viewModel->getJsonConfig($storeId); ?>
    <?php if ($jsonConfig): ?>
        <script>
            Extend.config(<?= $viewModel->getJsonConfig($storeId) ?>);
        </script>
    <?php endif; ?>
<?php endif; ?>
